class MyList {
  static List tags = [
    'Java',
    'Php',
    'C++',
    'Css',
    'C',
    'Technology',
    'Html',
    'Algorithm',
    'React',
    'Dart',
    'C#',
    '3D',
    'AI',
    'IOT',
    'Python',
    'Framework',
    'Backend',
    'Frontend',
    'JavaScript',
    'Angular',
    'Web',
    'Mobile',
    'Mathematics',
    'physics',
    'IT',
    'Machine Learning',
    'Internet security',
    'Softwear',
    'Artificial Intelligence',
    'Internet of things',
    'web development',
    'Graphic design',
    'machine learning',
    'web security',
    'Database',
    'Big data'
  ];
}
