// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPQSAwd5XFdsOeUBYRpvbRfu2_IuA6_yc',
    appId: '1:480468269943:web:6b8ca4ddf20aae3f3d7f72',
    messagingSenderId: '480468269943',
    projectId: 'asky-6cd79',
    authDomain: 'asky-6cd79.firebaseapp.com',
    storageBucket: 'asky-6cd79.appspot.com',
    measurementId: 'G-SK0PTC01RS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZO7GaknTU1xC7sxUOhiLFxa6WODyCFTQ',
    appId: '1:480468269943:android:a33192b582ec72e33d7f72',
    messagingSenderId: '480468269943',
    projectId: 'asky-6cd79',
    storageBucket: 'asky-6cd79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApaEhKQBqFBls8OPzskhKfIJM1jvFCkdU',
    appId: '1:480468269943:ios:accf84e68f40dea93d7f72',
    messagingSenderId: '480468269943',
    projectId: 'asky-6cd79',
    storageBucket: 'asky-6cd79.appspot.com',
    androidClientId: '480468269943-dhhivb29s1cvn0up2pa207n93idrqsnl.apps.googleusercontent.com',
    iosClientId: '480468269943-dqa721rnud0v0mahvjiuobcghic2ebeq.apps.googleusercontent.com',
    iosBundleId: 'tn.asky.asky.asky',
  );
}
